# Generated by Django 4.2.2 on 2023-06-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rassrochka', models.DateTimeField(auto_now_add=True)),
                ('every_pays', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('own_partifition', models.IntegerField()),
                ('installment_balance', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('number_cart', models.IntegerField()),
                ('valid_about', models.IntegerField()),
            ],
        ),
    ]
