# Generated by Django 4.2.2 on 2023-08-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
            ],
        ),
    ]
