# Generated by Django 4.2.2 on 2023-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='merchant',
            new_name='name_bank',
        ),
        migrations.AddField(
            model_name='merchant',
            name='addres',
            field=models.TextField(default='USA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='bank_number',
            field=models.IntegerField(default=45678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='mfo',
            field=models.IntegerField(default=5678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='name_shop',
            field=models.CharField(default='Nike', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='phone_number',
            field=models.IntegerField(default=45678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='type_merchant',
            field=models.CharField(default='Managemant', max_length=100),
            preserve_default=False,
        ),
    ]
