# Generated by Django 4.2.2 on 2023-06-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reste', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnfl', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_number', models.IntegerField()),
                ('issued', models.CharField(max_length=100)),
                ('date_give', models.DateTimeField(auto_now_add=True)),
                ('goden_about', models.DateTimeField(auto_now_add=True)),
                ('nationality', models.CharField(max_length=100)),
                ('citizienship', models.CharField(max_length=100)),
                ('whos_addres', models.CharField(max_length=100)),
                ('whos_number', models.IntegerField()),
                ('number_card', models.IntegerField()),
                ('term_card', models.IntegerField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reste.merchant')),
            ],
        ),
    ]
